name: Validate JSONs and Donation files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check files in donations.yml
        uses: mikefarah/yq@v4.6.1
        with:
          cmd: "ls -la /*/donations.yml; for F in /*/donations.yml; do yq e '[].files' $F | while read PROOF; do echo -n $PROOF; [ ! -f $PROOF] && echo ' does not exist' && exit; echo exists; done; done"

      - name: Create jsons out of donations.yml
        uses: mikefarah/yq@4.0.0-beta1
        with:
          cmd: |
            for F in /*/donations.yml
            do 
              DEST=${F/yml/json}
              cat $F | yq - -j > $DEST
              cat $DEST
            done

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: .github/schemas/donations.json
          INPUT_JSONS: "/*/donations.json"


